// Autogenerated by gulp scripts. Do not edit
window.AppConfig = {
    "config": {
        "app_title": "Phoenix",
        "app_name_about": "Phoenix",
        "about_icon": "styles/images/phoenix-icon.svg",
        "how_to_use_url": "https://github.com/adobe/brackets/wiki/How-to-Use-Brackets",
        "support_url": "https://github.com/phcode-dev/phoenix/discussions",
        "suggest_feature_url": "https://github.com/phcode-dev/phoenix/discussions/categories/ideas",
        "get_involved_url": "https://github.com/phcode-dev/phoenix/discussions/77",
        "glob_help_url": "https://github.com/adobe/brackets/wiki/Using-File-Filters",
        "release_notes_url": "https://github.com/adobe/brackets/wiki/Release-Notes",
        "homepage_url": "https://core.ai",
        "twitter_url": "https://twitter.com/phcodedev",
        "troubleshoot_url": "https://github.com/adobe/brackets/wiki/Troubleshooting#wiki-livedev",
        "twitter_name": "@phcodedev",
        "contributors_url": "https://api.github.com/repos/phcode-dev/phoenix/contributors?per_page={0}&page={1}",
        "extension_listing_url": "",
        "extension_registry": "https://extensions.phcode.dev/registry.json",
        "extension_registry_version": "https://extensions.phcode.dev/registry_version.json",
        "extension_url": "https://extensions.phcode.dev/extensions/",
        "extension_store_url": "https://store.core.ai/src/",
        "linting.enabled_by_default": true,
        "build_timestamp": "2023-01-24T10:08:52.939Z",
        "googleAnalyticsID": "G-FP5S9BKDSJ",
        "mixPanelID": "a7e08ffd43c37767c29b13df1d2e6c62",
        "coreAnalyticsID": "phoenix",
        "coreAnalyticsAppName": "phoenix-stage",
        "environment": "stage",
        "buildtype": "staging",
        "bugsnagEnv": "staging"
    },
    "name": "Phoenix",
    "version": "3.1.9-19161",
    "apiVersion": "3.1.9",
    "homepage": "https://core.ai",
    "issues": {
        "url": "https://github.com/phcode-dev/phoenix/issues"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/phcode-dev/phoenix.git",
        "branch": "",
        "SHA": ""
    },
    "licenses": [
        {
            "type": "AGPL-3.0-or-later",
            "url": "https://github.com/phcode-dev/phoenix/blob/master/LICENSE"
        }
    ]
};
