// Autogenerated by gulp scripts. Do not edit
window.AppConfig = {
    "config": {
        "app_title": "Phoenix Code",
        "app_name_about": "Phoenix Code",
        "main_pro_plan": "Phoenix Pro",
        "main_pro_plan_short": "Pro",
        "ai_brand_name": "Phoenix AI",
        "about_icon": "styles/images/phoenix-icon.svg",
        "account_url": "https://account-stage.phcode.dev/",
        "promotions_url": "https://promotions.phcode.dev/dev/",
        "purchase_url": "https://phcode.io/pricing",
        "license_url": "https://www.gnu.org/licenses/agpl-3.0.en.html",
        "how_to_use_url": "https://github.com/adobe/brackets/wiki/How-to-Use-Brackets",
        "docs_url": "https://docs.phcode.dev/",
        "support_url": "https://account.phcode.dev/?returnUrl=https%3A%2F%2Faccount.phcode.dev%2F%23support",
        "suggest_feature_url": "https://github.com/phcode-dev/phoenix/discussions/categories/ideas",
        "report_issue_url": "https://github.com/phcode-dev/phoenix/issues/new/choose",
        "get_involved_url": "https://github.com/phcode-dev/phoenix/discussions/77",
        "release_notes_url": "https://github.com/adobe/brackets/wiki/Release-Notes",
        "homepage_url": "https://phcode.io",
        "update_download_page": "https://phcode.io/",
        "twitter_url": "https://twitter.com/phcodedev",
        "youtube_url": "https://www.youtube.com/channel/UCNK2a8DKqPQQe3GlfTk-RHg",
        "troubleshoot_url": "https://github.com/adobe/brackets/wiki/Troubleshooting#wiki-livedev",
        "twitter_name": "@phcodedev",
        "contributors_url": "https://api.github.com/repos/phcode-dev/phoenix/contributors?per_page={0}&page={1}",
        "extension_listing_url": "",
        "extension_registry": "https://extensions.phcode.dev/registry.json",
        "extension_registry_version": "https://extensions.phcode.dev/registry_version.json",
        "extension_registry_popularity": "https://extensions.phcode.dev/popularity.json",
        "extension_url": "https://extensions.phcode.dev/extensions/",
        "extension_store_url": "https://store.core.ai/src/",
        "app_notification_url": "https://updates.phcode.io/appNotifications/staging/",
        "app_update_url": "https://updates.phcode.io/tauri/update-latest-pre-release.json",
        "extensionTakedownURL": "https://updates.phcode.io/extension_takedown.json",
        "lsp_server_pins": {
            "intelephense": "1.18.5",
            "pyrefly": "1.1.1",
            "ruff": "0.15.20"
        },
        "linting.enabled_by_default": true,
        "build_timestamp": "2026-08-27T10:30:38.370Z",
        "googleAnalyticsID": "G-FP5S9BKDSJ",
        "googleAnalyticsIDDesktop": "G-D5R1Y6PTS8",
        "mixPanelID": "a7e08ffd43c37767c29b13df1d2e6c62",
        "coreAnalyticsID": "phoenix",
        "coreAnalyticsAppName": "phoenix-stage",
        "coreAnalyticsAppNameDesktop": "desktop-stage",
        "environment": "stage",
        "buildtype": "staging",
        "bugsnagEnv": "staging"
    },
    "name": "Phoenix Code",
    "version": "5.3.0-23346",
    "apiVersion": "5.3.0",
    "homepage": "https://core.ai",
    "issues": {
        "url": "https://github.com/phcode-dev/phoenix/issues"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/phcode-dev/phoenix.git",
        "branch": "",
        "SHA": ""
    },
    "licenses": [
        {
            "type": "AGPL-3.0-or-later",
            "url": "https://github.com/phcode-dev/phoenix/blob/master/LICENSE"
        }
    ]
};
